blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/rkaufman13/rachels-extremely-cool-test-package/discussions
    about: Please ask and answer questions here.
